# Generated by Django 5.0 on 2024-03-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='discription',
            new_name='description',
        ),
    ]
