# Generated by Django 5.0 on 2024-03-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0010_alter_apply_applydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='applydate',
            field=models.DateField(),
        ),
    ]
