# Generated by Django 5.0 on 2024-04-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=110)),
                ('skills', models.CharField(max_length=110)),
                ('project', models.CharField(max_length=150)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.studentuser')),
            ],
        ),
    ]
