# Generated by Django 5.0 on 2024-03-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_recruiteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteruser',
            name='company',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='recruiteruser',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
