# Generated by Django 5.0 on 2024-03-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0009_remove_studentuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='applydate',
            field=models.DateTimeField(),
        ),
    ]
